### ISSUE TITLE
Add validations for each Swipe Step

### ISSUE THREAD

**Issue by I-am-abdulazeez** [aaronksaunders/react-hook-form-wizard-example#2]
How can we achieve the validation step for each swipe? 

Example: 

if I have the `Firstname` and the `Lastname` fields expected to be valid for the first step:

```
const next = async (fields: any) => {
    const result = await trigger(fields);
   // Check if the fields are valid before going to the next step here...
    if (!result) return;
    await mySlides?.slideNext();
  };
```

Also if the fields are not valid, disable the `button` to `Next Step`

Something like this sir: **_https://github.com/react-hook-form/react-hook-form/discussions/4028_**

**Comment by aaronksaunders** [comment]
it already blocks moving forward if the fields are not valid

--

Aaron K. SaundersCEO Clearly Innovative Inc
***@***.***
www.clearlyinnovative.com

This email message and any attachment(s) are for the sole use of the intended
recipient(s) and may contain proprietary and/or confidential information which
may be privileged or otherwise protected from disclosure. Any unauthorized
review, use, disclosure or distribution is prohibited. If you are not the
intended recipient(s), please contact the sender by reply email  and destroy the
original message and any copies of the message as well as any attachment(s) to
the original message.  





On Thu, Mar 31, 2022 at 7:29 PM AbdulAzeez Olanrewaju ***@***.***> 
 wrote:


How can we achieve the validation step for each swipe?

Example:

if I have the Firstname  and the Lastname  fields expected to be valid for the
first step:

const next = async (fields: any) => {
    const result = await trigger(fields);
   // Check if the fields are valid before going to the next step here...
    if (!result) return;
    await mySlides?.slideNext();
  };


Also if the fields are not valid, disable the button  to Next Step

Something like this sir: react-hook-form/react-hook-form#4028

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: 
***@***.***>

**Comment by aaronksaunders** [comment]
This is a feature request not an issue

**Comment by I-am-abdulazeez** [comment]
Ok, but how do I disable the `next button` until the first fields are filled by the user.

like the `!isValid` and `!isDirty` is been used on the fields, if I use that, it tries to check the whole field. but, I want it to check the first field in the first step.

Sorry for any inconvenience...
